spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ums}
    username: ${DB_USER:postgres}
    password: ${DB_PW:postgres}
    driver-class-name: ${DRIVER_CLASS:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
